### PR TITLE
More show improvements

### LINKED ISSUE #176: `show` bug with LibGEOS.Polygon
```julia
using GeometryBasics, GeoInterface, GeometryOps, LibGEOS

v = [Point2(0.0, 0.0), Point2(0.0, 1.0), Point2(1.0, 1.0), Point2(1.0, 0.0), Point2(0.0, 0.0)]
p = GeoInterface.Polygon([GeoInterface.LinearRing(v)])
GeometryOps.intersection(GeometryOps.GEOS(), p, p)
```

hits
```julia
Error showing value of type GeoInterface.Wrappers.Polygon{false, false, LibGEOS.Polygon, Nothing, Nothing}:
ERROR: UndefVarError: `g` not defined in `GeoInterface.Wrappers`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
  [1] show(io::IOContext{…}, ::MIME{…}, geom::GeoInterface.Wrappers.Polygon{…}; show_mz::Bool, screen_ncols::Int64)
    @ GeoInterface.Wrappers ~/.julia/packages/GeoInterface/rJdrx/src/wrappers.jl:237
  [2] show(io::IOContext{…}, ::MIME{…}, geom::GeoInterface.Wrappers.Polygon{…})
    @ GeoInterface.Wrappers ~/.julia/packages/GeoInterface/rJdrx/src/wrappers.jl:175
```

### PR DESCRIPTION
**Pull request by asinghvi17**
Supersedes #177 
Fix #176 #182

#### actual changes
- forward 2-arg show(io, geom) to 3-arg show(io, MIME"text/plain"(), geom)
- Wrap CRS in quotes when showing, so that geometries can be copy/pasted at least
#### bugfixes and tests
- bugfix missing or wrongly named variables / typos when showing wrapper geometries
- bugfix show
- fix point show by adding a screen_ncols kwarg
- use sprint() instead of global IOBuffers in testing, so that it can be made interactive
- force display size to be consistent in the test function
- Test the printing of wrapped (rapped ;)) geometries

### CODE REVIEW

**Comment by asinghvi17** [comment]
CI is finally green!!

File: test/test_wrappers.jl [hunk 1]
```diff
@@ -80,7 +80,7 @@ test_display(pointm, "Point{false, true}((1, 2, 3))", "Point((1,2,3))")
 pointm_crs = GI.Point((X=1, Y=2, M=3); crs=EPSG(4326))
 @test parent(pointm_crs) === parent(pointm)
 @test GI.crs(pointm_crs) === EPSG(4326)
-test_display(pointm_crs, "Point{false, true}((1, 2, 3), crs = EPSG{1}((4326,)))", "Point((1,2,3))")
+test_display(pointm_crs, "Point{false, true}((1, 2, 3), crs = \"EPSG:4326\")", "Point((1,2,3))")
```
Comment (rafaqz) [inline test/test_wrappers.jl:83]: I wonder if showing EPSG as a string is confusing to users who still need to use the constructor

**Review by rafaqz — APPROVED** [review]

File: test/test_wrappers.jl (hunk 1 above)
Comment (asinghvi17) [reply test/test_wrappers.jl:83]: Agreed, but it's equivalent in most cases that one might care about (Proj and GDAL)

Comment (asinghvi17) [reply test/test_wrappers.jl:83]: Maybe we should change show on GFT types to show the constructor too?
